[project]
name = "minecraft-discord-whitelist-status-bot"
version = "1.0.0"
description = "Discord bot for managing Minecraft server whitelist with username validation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["discord-py>=2.3.2", "aiohttp>=3.9.0", "mcrcon>=0.7.0"]
